/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorisedRouteImport } from './routes/unauthorised'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentTemplatesRouteImport } from './routes/agent.templates'
import { Route as AgentReviewsRouteImport } from './routes/agent.reviews'
import { Route as AgentReferralsRouteImport } from './routes/agent.referrals'
import { Route as AgentLeadsRouteImport } from './routes/agent.leads'
import { Route as AgentDashboardRouteImport } from './routes/agent.dashboard'
import { Route as AgentBillingRouteImport } from './routes/agent.billing'
import { Route as AgentAnalyticsRouteImport } from './routes/agent.analytics'
import { Route as AgentPackagesIndexRouteImport } from './routes/agent.packages.index'
import { Route as AgentCampaignsIndexRouteImport } from './routes/agent.campaigns.index'
import { Route as ApiAuthSignoutAllDevicesRouteImport } from './routes/api.auth.signout-all-devices'
import { Route as AgentTemplatesQuotesRouteImport } from './routes/agent.templates.quotes'
import { Route as AgentPackagesNewRouteImport } from './routes/agent.packages.new'
import { Route as AgentOnboardingCredentialsRouteImport } from './routes/agent.onboarding.credentials'
import { Route as AgentContentNewRouteImport } from './routes/agent.content.new'
import { Route as AgentCampaignsNewRouteImport } from './routes/agent.campaigns.new'
import { Route as AgentAdvertisingFeaturedRouteImport } from './routes/agent.advertising.featured'
import { Route as AgentPackagesIdEditRouteImport } from './routes/agent.packages.$id.edit'
import { Route as AgentPackagesIdAvailabilityRouteImport } from './routes/agent.packages.$id.availability'

const UnauthorisedRoute = UnauthorisedRouteImport.update({
  id: '/unauthorised',
  path: '/unauthorised',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTemplatesRoute = AgentTemplatesRouteImport.update({
  id: '/agent/templates',
  path: '/agent/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentReviewsRoute = AgentReviewsRouteImport.update({
  id: '/agent/reviews',
  path: '/agent/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentReferralsRoute = AgentReferralsRouteImport.update({
  id: '/agent/referrals',
  path: '/agent/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLeadsRoute = AgentLeadsRouteImport.update({
  id: '/agent/leads',
  path: '/agent/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentBillingRoute = AgentBillingRouteImport.update({
  id: '/agent/billing',
  path: '/agent/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAnalyticsRoute = AgentAnalyticsRouteImport.update({
  id: '/agent/analytics',
  path: '/agent/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPackagesIndexRoute = AgentPackagesIndexRouteImport.update({
  id: '/agent/packages/',
  path: '/agent/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCampaignsIndexRoute = AgentCampaignsIndexRouteImport.update({
  id: '/agent/campaigns/',
  path: '/agent/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutAllDevicesRoute =
  ApiAuthSignoutAllDevicesRouteImport.update({
    id: '/api/auth/signout-all-devices',
    path: '/api/auth/signout-all-devices',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentTemplatesQuotesRoute = AgentTemplatesQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AgentTemplatesRoute,
} as any)
const AgentPackagesNewRoute = AgentPackagesNewRouteImport.update({
  id: '/agent/packages/new',
  path: '/agent/packages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentOnboardingCredentialsRoute =
  AgentOnboardingCredentialsRouteImport.update({
    id: '/agent/onboarding/credentials',
    path: '/agent/onboarding/credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentContentNewRoute = AgentContentNewRouteImport.update({
  id: '/agent/content/new',
  path: '/agent/content/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCampaignsNewRoute = AgentCampaignsNewRouteImport.update({
  id: '/agent/campaigns/new',
  path: '/agent/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAdvertisingFeaturedRoute =
  AgentAdvertisingFeaturedRouteImport.update({
    id: '/agent/advertising/featured',
    path: '/agent/advertising/featured',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentPackagesIdEditRoute = AgentPackagesIdEditRouteImport.update({
  id: '/agent/packages/$id/edit',
  path: '/agent/packages/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPackagesIdAvailabilityRoute =
  AgentPackagesIdAvailabilityRouteImport.update({
    id: '/agent/packages/$id/availability',
    path: '/agent/packages/$id/availability',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/unauthorised': typeof UnauthorisedRoute
  '/agent/analytics': typeof AgentAnalyticsRoute
  '/agent/billing': typeof AgentBillingRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/referrals': typeof AgentReferralsRoute
  '/agent/reviews': typeof AgentReviewsRoute
  '/agent/templates': typeof AgentTemplatesRouteWithChildren
  '/agent/advertising/featured': typeof AgentAdvertisingFeaturedRoute
  '/agent/campaigns/new': typeof AgentCampaignsNewRoute
  '/agent/content/new': typeof AgentContentNewRoute
  '/agent/onboarding/credentials': typeof AgentOnboardingCredentialsRoute
  '/agent/packages/new': typeof AgentPackagesNewRoute
  '/agent/templates/quotes': typeof AgentTemplatesQuotesRoute
  '/api/auth/signout-all-devices': typeof ApiAuthSignoutAllDevicesRoute
  '/agent/campaigns/': typeof AgentCampaignsIndexRoute
  '/agent/packages/': typeof AgentPackagesIndexRoute
  '/agent/packages/$id/availability': typeof AgentPackagesIdAvailabilityRoute
  '/agent/packages/$id/edit': typeof AgentPackagesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/unauthorised': typeof UnauthorisedRoute
  '/agent/analytics': typeof AgentAnalyticsRoute
  '/agent/billing': typeof AgentBillingRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/referrals': typeof AgentReferralsRoute
  '/agent/reviews': typeof AgentReviewsRoute
  '/agent/templates': typeof AgentTemplatesRouteWithChildren
  '/agent/advertising/featured': typeof AgentAdvertisingFeaturedRoute
  '/agent/campaigns/new': typeof AgentCampaignsNewRoute
  '/agent/content/new': typeof AgentContentNewRoute
  '/agent/onboarding/credentials': typeof AgentOnboardingCredentialsRoute
  '/agent/packages/new': typeof AgentPackagesNewRoute
  '/agent/templates/quotes': typeof AgentTemplatesQuotesRoute
  '/api/auth/signout-all-devices': typeof ApiAuthSignoutAllDevicesRoute
  '/agent/campaigns': typeof AgentCampaignsIndexRoute
  '/agent/packages': typeof AgentPackagesIndexRoute
  '/agent/packages/$id/availability': typeof AgentPackagesIdAvailabilityRoute
  '/agent/packages/$id/edit': typeof AgentPackagesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/unauthorised': typeof UnauthorisedRoute
  '/agent/analytics': typeof AgentAnalyticsRoute
  '/agent/billing': typeof AgentBillingRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/referrals': typeof AgentReferralsRoute
  '/agent/reviews': typeof AgentReviewsRoute
  '/agent/templates': typeof AgentTemplatesRouteWithChildren
  '/agent/advertising/featured': typeof AgentAdvertisingFeaturedRoute
  '/agent/campaigns/new': typeof AgentCampaignsNewRoute
  '/agent/content/new': typeof AgentContentNewRoute
  '/agent/onboarding/credentials': typeof AgentOnboardingCredentialsRoute
  '/agent/packages/new': typeof AgentPackagesNewRoute
  '/agent/templates/quotes': typeof AgentTemplatesQuotesRoute
  '/api/auth/signout-all-devices': typeof ApiAuthSignoutAllDevicesRoute
  '/agent/campaigns/': typeof AgentCampaignsIndexRoute
  '/agent/packages/': typeof AgentPackagesIndexRoute
  '/agent/packages/$id/availability': typeof AgentPackagesIdAvailabilityRoute
  '/agent/packages/$id/edit': typeof AgentPackagesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/unauthorised'
    | '/agent/analytics'
    | '/agent/billing'
    | '/agent/dashboard'
    | '/agent/leads'
    | '/agent/referrals'
    | '/agent/reviews'
    | '/agent/templates'
    | '/agent/advertising/featured'
    | '/agent/campaigns/new'
    | '/agent/content/new'
    | '/agent/onboarding/credentials'
    | '/agent/packages/new'
    | '/agent/templates/quotes'
    | '/api/auth/signout-all-devices'
    | '/agent/campaigns/'
    | '/agent/packages/'
    | '/agent/packages/$id/availability'
    | '/agent/packages/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/unauthorised'
    | '/agent/analytics'
    | '/agent/billing'
    | '/agent/dashboard'
    | '/agent/leads'
    | '/agent/referrals'
    | '/agent/reviews'
    | '/agent/templates'
    | '/agent/advertising/featured'
    | '/agent/campaigns/new'
    | '/agent/content/new'
    | '/agent/onboarding/credentials'
    | '/agent/packages/new'
    | '/agent/templates/quotes'
    | '/api/auth/signout-all-devices'
    | '/agent/campaigns'
    | '/agent/packages'
    | '/agent/packages/$id/availability'
    | '/agent/packages/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/unauthorised'
    | '/agent/analytics'
    | '/agent/billing'
    | '/agent/dashboard'
    | '/agent/leads'
    | '/agent/referrals'
    | '/agent/reviews'
    | '/agent/templates'
    | '/agent/advertising/featured'
    | '/agent/campaigns/new'
    | '/agent/content/new'
    | '/agent/onboarding/credentials'
    | '/agent/packages/new'
    | '/agent/templates/quotes'
    | '/api/auth/signout-all-devices'
    | '/agent/campaigns/'
    | '/agent/packages/'
    | '/agent/packages/$id/availability'
    | '/agent/packages/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  UnauthorisedRoute: typeof UnauthorisedRoute
  AgentAnalyticsRoute: typeof AgentAnalyticsRoute
  AgentBillingRoute: typeof AgentBillingRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentLeadsRoute: typeof AgentLeadsRoute
  AgentReferralsRoute: typeof AgentReferralsRoute
  AgentReviewsRoute: typeof AgentReviewsRoute
  AgentTemplatesRoute: typeof AgentTemplatesRouteWithChildren
  AgentAdvertisingFeaturedRoute: typeof AgentAdvertisingFeaturedRoute
  AgentCampaignsNewRoute: typeof AgentCampaignsNewRoute
  AgentContentNewRoute: typeof AgentContentNewRoute
  AgentOnboardingCredentialsRoute: typeof AgentOnboardingCredentialsRoute
  AgentPackagesNewRoute: typeof AgentPackagesNewRoute
  ApiAuthSignoutAllDevicesRoute: typeof ApiAuthSignoutAllDevicesRoute
  AgentCampaignsIndexRoute: typeof AgentCampaignsIndexRoute
  AgentPackagesIndexRoute: typeof AgentPackagesIndexRoute
  AgentPackagesIdAvailabilityRoute: typeof AgentPackagesIdAvailabilityRoute
  AgentPackagesIdEditRoute: typeof AgentPackagesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorised': {
      id: '/unauthorised'
      path: '/unauthorised'
      fullPath: '/unauthorised'
      preLoaderRoute: typeof UnauthorisedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/templates': {
      id: '/agent/templates'
      path: '/agent/templates'
      fullPath: '/agent/templates'
      preLoaderRoute: typeof AgentTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/reviews': {
      id: '/agent/reviews'
      path: '/agent/reviews'
      fullPath: '/agent/reviews'
      preLoaderRoute: typeof AgentReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/referrals': {
      id: '/agent/referrals'
      path: '/agent/referrals'
      fullPath: '/agent/referrals'
      preLoaderRoute: typeof AgentReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/leads': {
      id: '/agent/leads'
      path: '/agent/leads'
      fullPath: '/agent/leads'
      preLoaderRoute: typeof AgentLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/billing': {
      id: '/agent/billing'
      path: '/agent/billing'
      fullPath: '/agent/billing'
      preLoaderRoute: typeof AgentBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/analytics': {
      id: '/agent/analytics'
      path: '/agent/analytics'
      fullPath: '/agent/analytics'
      preLoaderRoute: typeof AgentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/packages/': {
      id: '/agent/packages/'
      path: '/agent/packages'
      fullPath: '/agent/packages/'
      preLoaderRoute: typeof AgentPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/campaigns/': {
      id: '/agent/campaigns/'
      path: '/agent/campaigns'
      fullPath: '/agent/campaigns/'
      preLoaderRoute: typeof AgentCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout-all-devices': {
      id: '/api/auth/signout-all-devices'
      path: '/api/auth/signout-all-devices'
      fullPath: '/api/auth/signout-all-devices'
      preLoaderRoute: typeof ApiAuthSignoutAllDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/templates/quotes': {
      id: '/agent/templates/quotes'
      path: '/quotes'
      fullPath: '/agent/templates/quotes'
      preLoaderRoute: typeof AgentTemplatesQuotesRouteImport
      parentRoute: typeof AgentTemplatesRoute
    }
    '/agent/packages/new': {
      id: '/agent/packages/new'
      path: '/agent/packages/new'
      fullPath: '/agent/packages/new'
      preLoaderRoute: typeof AgentPackagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/onboarding/credentials': {
      id: '/agent/onboarding/credentials'
      path: '/agent/onboarding/credentials'
      fullPath: '/agent/onboarding/credentials'
      preLoaderRoute: typeof AgentOnboardingCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/content/new': {
      id: '/agent/content/new'
      path: '/agent/content/new'
      fullPath: '/agent/content/new'
      preLoaderRoute: typeof AgentContentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/campaigns/new': {
      id: '/agent/campaigns/new'
      path: '/agent/campaigns/new'
      fullPath: '/agent/campaigns/new'
      preLoaderRoute: typeof AgentCampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/advertising/featured': {
      id: '/agent/advertising/featured'
      path: '/agent/advertising/featured'
      fullPath: '/agent/advertising/featured'
      preLoaderRoute: typeof AgentAdvertisingFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/packages/$id/edit': {
      id: '/agent/packages/$id/edit'
      path: '/agent/packages/$id/edit'
      fullPath: '/agent/packages/$id/edit'
      preLoaderRoute: typeof AgentPackagesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/packages/$id/availability': {
      id: '/agent/packages/$id/availability'
      path: '/agent/packages/$id/availability'
      fullPath: '/agent/packages/$id/availability'
      preLoaderRoute: typeof AgentPackagesIdAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentTemplatesRouteChildren {
  AgentTemplatesQuotesRoute: typeof AgentTemplatesQuotesRoute
}

const AgentTemplatesRouteChildren: AgentTemplatesRouteChildren = {
  AgentTemplatesQuotesRoute: AgentTemplatesQuotesRoute,
}

const AgentTemplatesRouteWithChildren = AgentTemplatesRoute._addFileChildren(
  AgentTemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  UnauthorisedRoute: UnauthorisedRoute,
  AgentAnalyticsRoute: AgentAnalyticsRoute,
  AgentBillingRoute: AgentBillingRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AgentLeadsRoute: AgentLeadsRoute,
  AgentReferralsRoute: AgentReferralsRoute,
  AgentReviewsRoute: AgentReviewsRoute,
  AgentTemplatesRoute: AgentTemplatesRouteWithChildren,
  AgentAdvertisingFeaturedRoute: AgentAdvertisingFeaturedRoute,
  AgentCampaignsNewRoute: AgentCampaignsNewRoute,
  AgentContentNewRoute: AgentContentNewRoute,
  AgentOnboardingCredentialsRoute: AgentOnboardingCredentialsRoute,
  AgentPackagesNewRoute: AgentPackagesNewRoute,
  ApiAuthSignoutAllDevicesRoute: ApiAuthSignoutAllDevicesRoute,
  AgentCampaignsIndexRoute: AgentCampaignsIndexRoute,
  AgentPackagesIndexRoute: AgentPackagesIndexRoute,
  AgentPackagesIdAvailabilityRoute: AgentPackagesIdAvailabilityRoute,
  AgentPackagesIdEditRoute: AgentPackagesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
